# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2f2ee6a2344279213956654cbe76a18d4da2c51c61061677c92f9f5a58d67f2eaec7553fd4fc56a4489550eb35857360f897fad86559783a38a50db12116f6b

test:
  secret_key_base: f2f42e0130f21b042031ef4647eca493daf210ddc1df19dfc42a2a8aa41b111185271d5e7f431cf3d17d525004fd9de73d5f5d8ced995969a17d55208eff58df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
